### ISSUE TITLE
Idea Edit/Delete

### ISSUE THREAD

**Issue by albatrocity** [cremalab/engagement-ring#13]
Kinda still wondering if an Idea should be able to be edited. Thoughts, @matao and @roblafeve

**Comment by roblafeve** [comment]
@albatrocity I was just wondering that too. I would say, let's just let a person edit everything for now OR they can only delete an idea and resubmit it if they screw up something? Which way do you lean?

**Comment by albatrocity** [comment]
@roblafeve the latter would be simplest. I had some edit functionality implemented last week, I'll see if it actually works.
