### ISSUE TITLE
Live Streaming Connection

### ISSUE THREAD

**Issue by byrgenwerth-freshman** [cremalab/engagement-ring#24]

**Comment by byrgenwerth-freshman** [comment]
@albatrocity This is the link for how to read SSE. http://www.html5rocks.com/en/tutorials/eventsource/basics/

**Comment by albatrocity** [comment]
@matao See the [jBuilder documentation](https://github.com/rails/jbuilder) to see if there's a way to render the show template for whatever object you're sending. If not, `object.as_json` will work.
