### ISSUE TITLE
Convert Sass to Stylus

### ISSUE THREAD

**Issue by roblafeve** [cremalab/engagement-ring#28]

**Comment by albatrocity** [comment]
@roblafeve so is the nested imports issue resolved in the latest version?

**Comment by roblafeve** [comment]
@albatrocity, Yeah, that's what it looks like.

**Comment by albatrocity** [comment]
Cool. Sorry to have to switch back over, but it's better if we keep this app all JS.

**Comment by roblafeve** [comment]
@albatrocity did you change the dependencies for this in Master?

**Comment by albatrocity** [comment]
Nope, it's just in the stylus branch. You can merge it into master when you're done.

**Comment by albatrocity** [comment]
@roblafeve also, you might have to delete your node_modules directory and run `npm install` again.

**Comment by roblafeve** [comment]
@albatrocity getting this:

error: { [Error: Component must have "/Users/Rob/Sites/engagement-ring/bower_components/js-md5/bower.json"] code: 'NO_BOWER_JSON' }

**Comment by roblafeve** [comment]
@albatrocity Oh… i didn't delete my node_modules dir. Dumb!

**Comment by roblafeve** [comment]
@albatrocity— buuuut still not working. Getting "ReferenceError: Can't find variable: moment" in console.

**Comment by albatrocity** [comment]
add `"main": "moment.js"` to bower_components/moment_js/component.json

**Comment by roblafeve** [comment]
That line already exists.

**Comment by roblafeve** [comment]
@albatrocity, OK just did a bower install and that fixed the issue. Thanks.
