### ISSUE TITLE
Profile UI Tweaks

### ISSUE THREAD

**Issue by roblafeve** [cremalab/engagement-ring#30]
- [x] Remove User email address from template
- [x] Look into Avatar size issue

**Comment by albatrocity** [comment]
@roblafeve the user email address is part of the votes/show template. It either shows the user's email address or their name if they have entered one. Are we not wanting to display who voted on ideas?

**Comment by roblafeve** [comment]
I see. What would that look like— "Ross, Rob, Kelly, and 3 others voted for this" ?

**Comment by albatrocity** [comment]
Yeah we could do that. Or little avatars or something. Depends on whether we want to keep voting anonymous or not.

**Comment by roblafeve** [comment]
I prefer the avatar route. I'll create some static markup for these if that makes sense.

**Comment by albatrocity** [comment]
No need to make them static, you can pull in the gravatar. I made a view helper that I'm using in the [idea show template](https://github.com/cremalab/engagement-ring/blob/master/app/views/ideas/templates/show.hbs#L3). You just need to pass it the email of the voter.
