### ISSUE TITLE
Destroy User Votes when Voter is removed

### ISSUE THREAD

**Issue by albatrocity** [cremalab/engagement-ring#43]
@matao @roblafeve do you guys agree with this? If someone is removed from a thread, their votes should be deleted since the thread owner probably doesn't care about their opinion.

**Comment by roblafeve** [comment]
@albatrocity— Agreed.

**Comment by byrgenwerth-freshman** [comment]
I concur.

**Comment by albatrocity** [comment]
This should actually probably happen on the API side. Made an issue for it [here](https://github.com/cremalab/suite_api/issues/66)
