### ISSUE TITLE
Does not automatically connect to faye server

### ISSUE THREAD

**Issue by byrgenwerth-freshman** [cremalab/engagement-ring#54]
@albatrocity So every time I'm logging in in the morning, I don't connect to the faye server. When I log out and log back in then I connect to the faye server. The things I think it could be is the session token doesn't get renewed. I'm not really sure what is going on. Are you experiencing this problem.

**Comment by albatrocity** [comment]
Could be that the localStorage hasn't kept your session key, or that it has actually changed. I don't have a check and reconnect method or anything. Probably something to roll in. But I'm not sure exactly what's causing this at the moment.

**Comment by byrgenwerth-freshman** [comment]
@albatrocity I'll keep you posted. I just wanted to document it. It isn't a huge deal. I just wanted to make sure we had it written down.
