### ISSUE TITLE
Idea Thread Styling

### ISSUE THREAD

**Issue by roblafeve** [cremalab/engagement-ring#6]

**Comment by roblafeve** [comment]
@albatrocity, I've branched off of "ideation" (ideation-style) to continue working on styling for this. I can't get any ideas to post— which may be because you aren't at a good point yet.

As a matter of process, how do we communicate that a branch is ready to have sub-features addressed?

**Comment by albatrocity** [comment]
@roblafeve if you update from the ideation branch you should be good now. Might need to delete all Ideas and Idea Threads.

**Comment by roblafeve** [comment]
Thank you sir!

**Comment by roblafeve** [comment]
Continued in #10

**Comment by roblafeve** [comment]
This is done and is in Master.
