### ISSUE TITLE
Show original idea in threads

### ISSUE THREAD

**Issue by albatrocity** [cremalab/engagement-ring#7]

**Comment by albatrocity** [comment]
@roblafeve How should this work? Do we just show the title? Do we make it a link that when clicked highlights the original or something? Any UI/UX ideas?

**Comment by roblafeve** [comment]
@albatrocity, yeah I was thinking about this too. I was thinking potentially just having a subtle indication that it was the 'original' instead of listing it out as it is in the mockup. Should we just add a class to the original idea? I could do something from there.

**Comment by albatrocity** [comment]
Whatever you think is best. Shouldn't be hard to implement either way.
