### ISSUE TITLE
Idea re-render on vote with comments bug

### ISSUE THREAD

**Issue by albatrocity** [cremalab/engagement-ring#80]
When having a comment form open, if someone else votes on something it unfocused the comment form.

**Comment by roblafeve** [comment]
:-1:

**Comment by albatrocity** [comment]
Actually... I don't know if I can reproduce this locally. Does this still happen on production? @roblafeve @matao

**Comment by albatrocity** [comment]
Tested it out, all it does is unfocus the comment form. I think I might know why.

**Comment by albatrocity** [comment]
fixed in 83d22eb6464c9d6755f90ed2aecaa41a2562ab56

**Comment by albatrocity** [comment]
When the idea you're focused on has its order in the collection changed, its view is re-rendered. Not sure exactly what happens yet, but something is not optimal.

**Comment by albatrocity** [comment]
Ultimately didn't solve this using #100. Instead I'm overriding the idea collection's sort method when focus is in the comment box. This may not even be an issue when the activity feed is moved to the sidebar, but it's fixed now. Still glad I did all the stuff for #100.
